steps:
- script: |
    echo hello world from $MyName
    echo Agent.HomeDirectory is $PWD
    echo ls
    echo Agent OS is $(agent.os)
    echo "##vso[task.setvariable variable=HostName]$MyName"
    export CHART_VERSION=$(cat demo-app-java/Chart.yaml | grep -m 1 ^version:| awk '{print $2}')
    echo chart version $CHART_VERSION
  workingDirectory: $(Agent.HomeDirectory)
  env:
    MyName: $(Agent.MachineName)
  condition: and(succeeded(), in(variables['agent.os'], 'darwin', 'linux'))
  displayName: Greeting from Linux

- script: |
    echo hello script 2
    echo My name is $machineName
    echo chart version2 $CHART_VERSION
  workingDirectory: $(Agent.HomeDirectory)
  env:
    machineName: $(HostName)
  condition: succeeded()
  displayName: Second Build Step