steps:
- script: |
    echo hello world from $MyName
    echo Agent.HomeDirectory is $PWD
    echo $(agent.os)
  workingDirectory: $(Agent.HomeDirectory)
  env:
    MyName: $(Agent.MachineName)
  condition: and(succeeded(), in(variables['agent.os'], 'darwin', 'linux'))
  displayName: Greeting from $(agent.os)