steps:
- script: |
    echo hello world from $MyName
    echo Agent.HomeDirectory is $PWD
    echo Agent OS is $(agent.os)
    echo "##vso[task.setvariable variable=HostName]$MyName"
    echo "##vso[task.setvariable variable=CHART_VERSION]$(cat demo-app-java/Chart.yaml | grep -m 1 ^version:| awk '{print $2}')"
    echo BranchName $BUILD_SOURCEBRANCHNAME
  workingDirectory: /opt/vsts/work/1/s
  env:
    MyName: $(Agent.MachineName)
  condition: and(succeeded(), in(variables['agent.os'], 'darwin', 'linux'))
  displayName: Greeting from Linux

- script: |
    echo hello script 2
    echo My name is $machineName
    echo chart version2 $CHART_VERSION
  workingDirectory: $(Agent.HomeDirectory)
  env:
    machineName: $(HostName)
    CHART_VERSION: $(CHART_VERSION)
  condition: succeeded()
  displayName: Second Build Step