steps:
- script: |
    echo hello world from $MyName
    echo Agent.HomeDirectory is $PWD
    echo Agent OS is $(agent.os)
  workingDirectory: $(Agent.HomeDirectory)
  env:
    MyName: $(Agent.MachineName)
  condition: and(succeeded(), in(variables['agent.os'], 'darwin', 'linux'))
  displayName: Greeting from Linux

- script: |
    echo hello script 2
    echo My name is $MyName
  workingDirectory: $(Agent.HomeDirectory)
  condition: succeeded()
  displayName: Second Build Step